name: Generate Pacman

on:
  schedule:
    - cron: "30 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: output

      - name: Generate pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Ethrineaa
          outputs: |
            pacman/pacman.svg
