name: Generate Pacman

on:
  schedule:
    - cron: "30 */12 * * *"
  workflow_dispatch:

jobs:
  pacman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Ethrineaa
          target_branch: output
          outputs: |
            pacman/pacman.svg
