name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: output

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Ethrineaa
          outputs: |
            snake/snake.svg
